'1.22.3'

In [12]:
vec = np.array([1,2,3,4,5])
print(vec)

[1 2 3 4 5]


In [17]:
mat = np.array([[1,2,3,4,5],['a','b','c','d','e']])
print(mat)
print('vec type: {},  mat type: {}'.format(type(vec), type(mat)))


[['1' '2' '3' '4' '5']
 ['a' 'b' 'c' 'd' 'e']]
vec type: <class 'numpy.ndarray'>,  mat type: <class 'numpy.ndarray'>


In [15]:
print('vec의 축개수: {}, 크기: {}'.format(vec.ndim, vec.shape))
print('mat의 축개수: {}, 크기: {}'.format(mat.ndim, mat.shape))


vec의 축개수: 1, 크기: (5,)
mat의 축개수: 2, 크기: (2, 5)


In [28]:
zero_mat = np.zeros((2,3))
print(zero_mat)
one_mat = np.ones((2,3))
print(one_mat)

specific_value_mat = np.full((2,3), 99)
print(specific_value_mat)

eye_mat = np.eye(3)
# random_mat = np.random.random_integers(low=1, high=10, size=3)
random_mat2 = np.random.random((3,3))
print(eye_mat)
# print(random_mat)
print(random_mat2)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[99 99 99]
 [99 99 99]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.26833955 0.4060544  0.95615114]
 [0.65873941 0.51046565 0.07652553]
 [0.55838663 0.80870079 0.38786342]]


In [39]:
range_vec = np.arange(10)
print(range_vec)

n= 3
range_n_step_vec = np.arange(1, 10, n)
print(range_n_step_vec)

input_mat = np.arange(30)
reshape_mat = np.array(np.arange(30)).reshape((5,int(input_mat.size/5)))
print(reshape_mat)


[0 1 2 3 4 5 6 7 8 9]
[1 4 7]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [43]:
before_sliced = np.array([[1,2],[3,4],[5,6]])
after_sliced = before_sliced[0,:]
print(after_sliced)
after_sliced = before_sliced[1,:]
print(after_sliced)
after_sliced = before_sliced[2,:]
print(after_sliced)
after_sliced = before_sliced[:,0]
print(after_sliced)
after_sliced = before_sliced[:,1]
print(after_sliced)
# after_sliced = before_sliced[:,2]
# print(after_sliced)

# 특정 인덱스 슬라이스
after_sliced = before_sliced[0,1]
print(after_sliced)
after_sliced = before_sliced[2,1]
print(after_sliced)
after_sliced = before_sliced[[2,1],[0,1]]
print(after_sliced)
# after_sliced = before_sliced[[2,1],[1,2]]
# print(after_sliced)


[1 2]
[3 4]
[5 6]
[1 3 5]
[2 4 6]
2
6
[5 4]


In [51]:
x = np.array([1,2,3])
y = np.array([4,5,6])

result = x+y
result = np.add(x,y)
print(result)
result = x-y
result = np.subtract(x,y)
print(result)
result = x*y
result = np.multiply(x,y)
print(result)
result = x/y
result = np.divide(x,y)
print(result)

mat1 = np.array(
    [[1,2],
     [4,5]] )
mat2 = np.array(
    [[1],
     [1]])
mat3 = np.dot(mat1, mat2)
print(mat3)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[[3]
 [9]]
